### ISSUE TITLE
Chapter 5 - Build Error QJsonObject

### ISSUE THREAD

**Issue by jhenzel** [PacktPublishing/End-to-End-GUI-development-with-Qt5#1]
I have been going through this code to better understand the structured approach taken.  In attempting to compile Chapter 5 of Module 1 I get the following error:

/Users/jph/Downloads/End-to-End-GUI-development-with-Qt5-master/Module 1/Chapter05/chapter5/cm/cm-lib/source/data/entity-collection.h:80: error: calling 'toObject' with incomplete return type 'QJsonObject'.  The offending line is `addEntity(new T(this, jsonValue.toObject()));`

void update(const QJsonArray& jsonArray) override
	{
		clear();
		for(const QJsonValue& jsonValue : jsonArray) {
            addEntity(new T(this, jsonValue.toObject()));
		}
	}

Any suggestions would be welcome as how to overcome this error.

I am on OSX 10.14.6 with Qt 5.13.0 clang 64bit.  Code has not been modified just downloaded directly from via Git

**Comment by tukaramhl** [comment]
For anyone who may encounter this problem, the _entity-collection.h_ header is missing a reference to QJsonObject:

`#include <QJsonObject>`
